// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASVHU2Uyv1qmRlKmTbEfxBuiTP9ijMQ7I',
    appId: '1:383193845980:web:cf8743a81ddf4b844aa419',
    messagingSenderId: '383193845980',
    projectId: 'glowing-service-368612',
    authDomain: 'glowing-service-368612.firebaseapp.com',
    storageBucket: 'glowing-service-368612.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKtNyFd7e46G4NyYeDWDp33Mo7cxipCds',
    appId: '1:383193845980:android:699df5c16cfc895d4aa419',
    messagingSenderId: '383193845980',
    projectId: 'glowing-service-368612',
    storageBucket: 'glowing-service-368612.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCssaMRchns5jlRwiy6AMaiRX2-uNMuEdM',
    appId: '1:383193845980:ios:3f444f997a2a3a104aa419',
    messagingSenderId: '383193845980',
    projectId: 'glowing-service-368612',
    storageBucket: 'glowing-service-368612.appspot.com',
    iosClientId: '383193845980-fkdosssvk7qli365hvf56v34jndoa50n.apps.googleusercontent.com',
    iosBundleId: 'com.example.termopanelescco',
  );
}
